// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// StartAuthSignUp implements startAuthSignUp operation.
//
// Starts the OAuth 2.0 authentication flow with the specified provider (Google, GitHub, etc.).
// On success, returns an authentication URL where the user should be redirected, and a state
// parameter to prevent CSRF attacks.
// This endpoint is primarily intended for calls from web frontends or CLI tools.
//
// POST /auth/sign-up/{provider}
func (UnimplementedHandler) StartAuthSignUp(ctx context.Context, req OptSignUpRequest, params StartAuthSignUpParams) (r StartAuthSignUpRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *SignUpErrorResponseStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *SignUpErrorResponseStatusCode) {
	r = new(SignUpErrorResponseStatusCode)
	return r
}
