apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlRENDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTkRnNU9ESXdOalF3SGhjTk1qVXdOakF6TWpBeU1UQTBXaGNOTXpVd05qQXhNakF5TVRBMApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTkRnNU9ESXdOalF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSc2x0c2JqSXB1YVNFc01yclpGVHNuN0YzSUF0VHdHN1RXQTZsNXlDbEMKQmJCNGdYT3dmREw3MWx1ZlBLNEVvQUhWWHl6RlBRd1NpTmlMQUxmYTQ2a2NvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVUZGU1BqRWIrbkFpVWVBbTI4T2JKCmtsV25tS3d3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQU51cWZvVmh2ZzlvSitaOTQ3aCs1Z25HdEc3WElsVkcKSU03YWJRMmwzN0xmQWlFQTk1UWFjcUNyUzQrY3NaVVFBSHNBMVY2MzUzWGNjVUtpT003MTFvQmpBTFE9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://192.168.11.10:6443
  name: local-k3s
contexts:
- context:
    cluster: local-k3s
    user: my-auth-user
  name: test-context
current-context: test-context
kind: Config
preferences: {}
users:
- name: my-auth-user
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1
      command: "./bin/test-auth-plugin"
      env:
      - name: "KUBE_AUTH_ISSUER_URL"
        value: "http://localhost:8080"
      - name: "KUBE_AUTH_TOKEN_URL"
        value: "http://localhost:8080/oauth/token"
      - name: "KUBE_AUTH_AUDIENCE"
        value: "kubernetes-api"
      - name: "KUBE_AUTH_CACHE_PATH"
        value: "/home/ksoroi/.kube/cache/auth-plugin/tokens.json"
      provideClusterInfo: false
      interactiveMode: Never